# Site
title: fernseed
url: https://fernseed.org

# Organisation
collections:
  fiction:
    output: true
    permalink: /:collection/:title/
permalink: /:slug/
paginate_path: '/archive/:num/'
images_path: '/images/'

# Contact
twitter:
  username: dmcgk
author: darren

# Build
lang: en
defaults:
  -
    scope:
      path: "" 
    values:
      layout: default
      author: darren
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
paginate: 20
small_image_threshold: 500w
micro_length: 280
inline_article_length: 1000

# Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-titles-from-headings
jekyll-mentions:
  base_url: 'https://twitter.com'
compress_html:
  comments: all
  clippings: none
  endings: none
  startings: none
