# Site settings
title: fernseed
url: https://fernseed.org
permalink: /:slug/
lang: en
paginate: 20
paginate_path: '/archive/:num/'
micro_length: 200
inline_article_length: 1000

# Contact settings
twitter:
  username: dmcgk
author: darren

# Build settings
defaults:
  -
    scope:
      path: "" 
    values:
      layout: default
      author: darren
markdown: kramdown
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-titles-from-headings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME

# Plugin settings
jekyll-mentions:
  base_url: 'https://twitter.com'
compress_html:
  comments: all
  clippings: none
  endings: none
  startings: none
